### ISSUE TITLE
Type error on Node property "drop"

### ISSUE THREAD

**Issue by justinmccann14** [open-source-labs/Svelvet#349] opened 2023-05-10 16:20 UTC
<img width="1046" alt="Screenshot 2023-05-10 at 11 17 47 AM" src="https://github.com/open-source-labs/Svelvet/assets/55098943/8ffa36a9-83a1-45df-abfd-6fd730e7b3b4">

We are getting a type error on the drop property for some reason.

Note: This property does work as expected but just shows a type error.

**Comment by briangregoryholmes** [comment] 2023-05-10 16:29
Can you confirm your version number? At least in our test projects, I'm not getting a similar error with the latest versions. Things like this are usually resolved by cleaning the npm cache or just doing an uninstall/reinstall of the library. I would also check node_modules > Svelvet > Components > Node > Node.svelte.d.ts. You should see that prop type there. The latest version has it on line 14.

**Comment by justinmccann14** [comment] 2023-05-10 16:47
```
Type '{ id: number; drop: string; }' is not assignable to type '{ position?: { x: number; y: number; } | undefined; dimensions?: InitialDimensions | null | undefined; id?: string | number | undefined; bgColor?: CSSColorString | null | undefined; ... 21 more ...; dynamic?: boolean | undefined; }'.
  Object literal may only specify known properties, and '"drop"' does not exist in type '{ position?: { x: number; y: number; } | undefined; dimensions?: InitialDimensions | null | undefined; id?: string | number | undefined; bgColor?: CSSColorString | null | undefined; ... 21 more ...; dynamic?: boolean | undefined; }'.ts(2322)
```

Here is the full error

**Comment by briangregoryholmes** [comment] 2023-05-11 00:52
Thanks, Justin. Sorry that you're dealing with this. I know how annoying linting issues can be. I haven't been able to reproduce this on my end just yet and scaffolding a new project with SvelteKit seems to be fine. I'll continue to poke around. 

We had a similar issue before with Svelte's type generation and it just required adding an explicit return definition to a function. Hopefully I can track something similar down.

**Comment by justinmccann14** [comment] 2023-05-11 03:25
No worries! It isn't a huge deal since everything is working but wanted to at least make you aware. I will keep digging as well and if I find anything I will let you know.

**Comment by justinmccann14** [comment] 2023-05-12 22:05
@briangregoryholmes This seems to have just gone away on its own. ¯\_(ツ)_/¯

**Comment by briangregoryholmes** [comment] 2023-05-12 22:53
My favorite kind of issue! Thanks for the PR, by the way. The team is working on the next major version for the next couple weeks, but we'll make sure it gets approved.

**Closed** 2023-05-13 14:55 UTC
