### ISSUE TITLE
Facing issues with Edge deletion

### ISSUE THREAD

**Issue by Akash-Sharma-1** [open-source-labs/Svelvet#270] opened 2023-04-21 18:34 UTC
Hi,
First of all, thank you for providing this awesome library <3
The new Svelvet 7 is even more awesome.

I was trying out the following example from the documentation (mentioned [here](https://svelvet.mintlify.app/components/edge)) : 
**MyEdge.svelte**

```html
<script>
	import { Edge } from 'svelvet';
</script>
<Edge let:path let:destroy edgeClick="{() => alert('Edge clicked')}" step>
  <path d={path} />
  <button on:click={destroy} slot="label">
    <p>Custom Label</p>
  </button>
</Edge>
<style>
	path {
		stroke: rgb(246, 231, 20);
		stroke-width: 4px;
	}
</style>

```

I used this custom edge in **MyNode.svelte**
```html
<script>
	import { Svelvet, Node } from 'svelvet';
    import MyEdge from './MyEdge.svelte
</script>

<Svelvet>
    <Node>
        <div class="my-node">
            <Anchor edge={MyEdge}/>
        </div>
    </Node>
</Svelvet>
```

The expectation was that after the edge was created, I can click on the button inside the edge to destory itself using {destroy}.
However, I am unable to click the button - I feel its a problem with z-index or something on similar lines.

Could you please help me in understanding the issue and are there any workarounds around it ?

**Comment by briangregoryholmes** [comment] 2023-04-21 18:44
Hi, Akash. Pushing a fix for this now that will be in v7.0.19 once I write the test. It was just an issue with our pointer-events setting. You should be able to fix this in the meantime by just putting `pointer-events: auto` on your button class.

**Comment by Akash-Sharma-1** [comment] 2023-04-21 18:46
Ohh I see, that's awesome !
I'll try the workaround.
Thanks for the help @briangregoryholmes  !

**Comment by briangregoryholmes** [comment] 2023-04-21 19:48
This fix is live now. Took longer than expected because I decided to restructure our test folder so that things run in parallel.

**Closed by briangregoryholmes** 2023-04-21 19:48 UTC

**Comment by Akash-Sharma-1** [comment] 2023-04-22 07:03
Hi @briangregoryholmes ,
I can still reproduce this issue in the latest version (v7.0.19)

However, the workaround is resolving the issue.

Thanks

**Comment by briangregoryholmes** [comment] 2023-04-22 13:56
@Akash-Sharma-1 I'm not able to reproduce the issue in the latest version. Here's a sandbox I threw together on 7.0.19. https://stackblitz.com/edit/vitejs-vite-zd3zfq?file=src/lib/CustomEdge.svelte

Hopefully we can track down the issue.
